version: '3'
services:
  device_control:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app/
      - ./logs:/usr/src/app/logs
    ports:
      - 5000:5000
    image: devicecontrol:latest
    container_name: MOTDeviceControl