version: '3'
services:
  device_control:
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - ${PORT_APP}:${PORT_APP}
    image: devicecontrol:latest
    container_name: MOTDeviceControl    
    volumes:
      - ${PWD}:/usr/src/app/
    networks:
      - networkDevControl
    dns: 
      - 8.8.8.8
      - 8.8.4.4
      
networks:
  networkDevControl:
    driver: bridge